@baseuri=https://tempstickapi.com/api/v1

GET {{baseuri}}/user
X-API-KEY: {{ApiKey}}

###

GET {{baseuri}}/sensor/{{SensorId}}
X-API-KEY: {{ApiKey}}

###

GET {{baseuri}}/sensor/{{SensorId}}/readings
X-API-KEY: {{ApiKey}}